# Starter pipeline
- task: RunFromFileSystemTask@5
  inputs:
    testPathInput: 'C:\Users\Administrator\Documents\UFT One'
    uploadArtifact: 'no'
    mcAuthType: 'basic'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
