package Model;
// Generated 26/01/2017 06:54:10 PM by Hibernate Tools 5.2.0.CR1

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidoP;
	private String apellidoM;
	private String email;
	private int idLocalidad;
	private int idIndustria;

	public Clientes() {
	}

	public Clientes(String nombre, String apellidoP, String apellidoM, String email, int idLocalidad, int idIndustria) {
		this.nombre = nombre;
		this.apellidoP = apellidoP;
		this.apellidoM = apellidoM;
		this.email = email;
		this.idLocalidad = idLocalidad;
		this.idIndustria = idIndustria;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidoP() {
		return this.apellidoP;
	}

	public void setApellidoP(String apellidoP) {
		this.apellidoP = apellidoP;
	}

	public String getApellidoM() {
		return this.apellidoM;
	}

	public void setApellidoM(String apellidoM) {
		this.apellidoM = apellidoM;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public int getIdIndustria() {
		return this.idIndustria;
	}

	public void setIdIndustria(int idIndustria) {
		this.idIndustria = idIndustria;
	}

}
