package Model;
// Generated 26/01/2017 06:54:10 PM by Hibernate Tools 5.2.0.CR1

/**
 * Tbestado generated by hbm2java
 */
public class Tbestado implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String clave;

	public Tbestado() {
	}

	public Tbestado(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
