package Model;
// Generated 26/01/2017 06:54:10 PM by Hibernate Tools 5.2.0.CR1

/**
 * Tbindustrias generated by hbm2java
 */
public class Tbindustrias implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int clave;

	public Tbindustrias() {
	}

	public Tbindustrias(String nombre, int clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getClave() {
		return this.clave;
	}

	public void setClave(int clave) {
		this.clave = clave;
	}

}
