package Model;
// Generated 27/01/2017 12:39:49 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tbindustrias generated by hbm2java
 */
public class Tbindustrias implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int clave;
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public Tbindustrias() {
	}

	public Tbindustrias(String nombre, int clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public Tbindustrias(String nombre, int clave, Set<Clientes> clienteses) {
		this.nombre = nombre;
		this.clave = clave;
		this.clienteses = clienteses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getClave() {
		return this.clave;
	}

	public void setClave(int clave) {
		this.clave = clave;
	}

	public Set<Clientes> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<Clientes> clienteses) {
		this.clienteses = clienteses;
	}

}
